apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "backend"
        dapr.io/app-port: "3001"
        dapr.io/log-level: "info"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - name: backend
        image: dapr-sample-backend:latest
        imagePullPolicy: Never  # For kind local images
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
  type: ClusterIP

---
# NodePort service for external access during testing
apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001
    protocol: TCP
  type: NodePort